### ISSUE TITLE
Support Mac with M1 chip

### ISSUE THREAD

**Issue by SVilgelm** [kyoh86/richgo#37]
Hi,
Could you please add the support of new Macs with M1 chip?

I see that you use the `goreleaser`, so in this case it's very simple, you need to add something like this:
```yaml
builds:
  - binary: "{{ .ProjectName }}"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
```

but you should use the go version 1.16 to build a proper binary.
