### ISSUE TITLE
bug: failed to import custom stylesheet

### ISSUE THREAD

**Issue by Davincible** [kyoh86/richgo#48]
I am trying to apply custom colors to the output, and created a stylesheet, but I can't get it to be pickedup by rich go. 

I have tried
```
~/.richstyle.yaml
{CWD}/.richstyle.yaml
{CWD}/.richstyle
```

Stylesheet:
```yaml
labelType: long
buildStyle:
  bold: true
  foreground: #f7bf23
startStyle:
  foreground: #454440
passStyle:
  foreground: #25bf0d
failStyle:
  bold: true
  foreground: #b80d0d
skipStyle:
  foreground: lightBlack
passPackageStyle:
  foreground: green
  hide: true
failPackageStyle:
  bold: true
  foreground: red
  hide: true
coverThreshold: 50
coveredStyle:
  foreground: green
uncoveredStyle:
  bold: true
  foreground: yellow
fileStyle:
  foreground: cyan
lineStyle:
  foreground: magenta
```

How can I debug this?
